/* Generated By:JavaCC: Do not edit this line. LatexLexerConstants.java */
package latexparser.javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LatexLexerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EOL = 1;
  /** RegularExpression Id. */
  int HEAD_BEGIN = 2;
  /** RegularExpression Id. */
  int HEAD_END = 3;
  /** RegularExpression Id. */
  int FOOT_BEGIN = 4;
  /** RegularExpression Id. */
  int FOOT_END = 5;
  /** RegularExpression Id. */
  int BLOCK_BEGIN = 6;
  /** RegularExpression Id. */
  int BLOCK_END = 7;
  /** RegularExpression Id. */
  int SPECS = 8;
  /** RegularExpression Id. */
  int PARAMS = 9;
  /** RegularExpression Id. */
  int TRUE_ITEM = 10;
  /** RegularExpression Id. */
  int SECTION = 11;
  /** RegularExpression Id. */
  int COMMENT_S = 12;
  /** RegularExpression Id. */
  int CHARS_IN_COMMENT = 13;
  /** RegularExpression Id. */
  int END_COMMENT = 14;
  /** RegularExpression Id. */
  int LPAR = 15;
  /** RegularExpression Id. */
  int LITERAL = 16;
  /** RegularExpression Id. */
  int EQUALS = 17;
  /** RegularExpression Id. */
  int RPAR = 18;
  /** RegularExpression Id. */
  int PARAM_ERR = 20;
  /** RegularExpression Id. */
  int B_LST = 21;
  /** RegularExpression Id. */
  int B_VRB = 22;
  /** RegularExpression Id. */
  int CHARS_IN_VERBAT = 23;
  /** RegularExpression Id. */
  int E_LST = 24;
  /** RegularExpression Id. */
  int E_VRB = 25;
  /** RegularExpression Id. */
  int VERBTOK = 26;
  /** RegularExpression Id. */
  int CHARS_IN_VERBTOK = 27;
  /** RegularExpression Id. */
  int EOL_IN_VERBTOK = 28;
  /** RegularExpression Id. */
  int ENUM_BEGIN = 29;
  /** RegularExpression Id. */
  int ENUM_END = 30;
  /** RegularExpression Id. */
  int ITEM = 31;
  /** RegularExpression Id. */
  int CHARS_IN_DEFAULT = 32;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_COMMENT = 1;
  /** Lexical state. */
  int IN_SP_PARAM = 2;
  /** Lexical state. */
  int IN_PARAM_INSIDE = 3;
  /** Lexical state. */
  int IN_VERBAT = 4;
  /** Lexical state. */
  int IN_VERBTOK = 5;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<EOL>",
    "\"%@Header.begin\"",
    "\"%@Header.end\"",
    "\"%@Footer.begin\"",
    "\"%@Footer.end\"",
    "\"%@QuestionBlock.begin\"",
    "\"%@QuestionBlock.end\"",
    "\"%@Specs\"",
    "\"%@Params\"",
    "\"%@T\"",
    "\"\\\\section\"",
    "\"%\"",
    "<CHARS_IN_COMMENT>",
    "<END_COMMENT>",
    "\"(\"",
    "<LITERAL>",
    "\"=\"",
    "\")\"",
    "<token of kind 19>",
    "<PARAM_ERR>",
    "\"\\\\begin{lstlisting}\"",
    "\"\\\\begin{verbatim}\"",
    "<CHARS_IN_VERBAT>",
    "\"\\\\end{lstlisting}\"",
    "\"\\\\end{verbatim}\"",
    "<VERBTOK>",
    "<CHARS_IN_VERBTOK>",
    "<EOL_IN_VERBTOK>",
    "\"\\\\begin{enumerate}\"",
    "\"\\\\end{enumerate}\"",
    "\"\\\\item\"",
    "<CHARS_IN_DEFAULT>",
  };

}
